spring:
  #默认数据库连接池相关配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bdservice?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

  rabbitmq:
#    host: 124.193.178.218
#    host: 192.168.4.12
#    host: 127.0.0.1
    host: 139.9.118.114
    port: 5672
    username: gyhd
    password: gyhd
    virtual-host: /

    #开启 confirm 确认机制
    publisher-confirms: true
    #开启 return 确认机制
    publisher-returns: true
    #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
    template:
      mandatory: true
  redis:
    host: localhost
    port: 6379
    timeout: 1000 #连接超时1000毫秒
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

# 自定义MQ配置信息
custom:
  rabbitMq:
    zhj:
      exchange: "MessageDown"
      queue: "bd.messagedown.queue"
      key: "zyyt.messagedown"
    tz:
      exchange: "MessageUp"
      queue: "bd.messageup.queue"
      key: "zyyt.messageup"
      DEAD_LETTER_EXCHANGE: "x-queue-type"
      DEAD_EXCHANGE: "classic"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: false
