spring:
  #默认数据库连接池相关配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lanzhou_system?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

  rabbitmq:
    host: 192.168.4.150
    port: 5672
    username: admin
    password: admin